apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.0.13
    chart: ingress-nginx
    helm:
      values: |
        controller:
          metrics:
            enabled: true
          podAnnotations:
            controller:
              metrics:
                service:
                  servicePort: "9090"
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
          replicaCount: 2
          service:
            type: LoadBalancer
          watchIngressWithoutClass: true
          ingressClassResource:
            default: true

  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
