apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    path: ''
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server'
    targetRevision: 3.8.2
    chart: metrics-server
    helm:
      values: |
        args:
          - --kubelet-insecure-tls

  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
